# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Employee name',
                'verbose_name_plural': 'Employee names',
            },
        ),
        migrations.CreateModel(
            name='Employeeteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Employee team',
                'verbose_name_plural': 'Employee teams',
            },
        ),
        migrations.AddField(
            model_name='employeename',
            name='employeeteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Employeeteam'),
        ),
    ]
